### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by vbsinha** [vbsinha/autojudge#48]
Here's the TODO list before the submission/evaluation on Thursday, May 2. Please keep on adding here and ticking off those which are completed.

- [x] CSV export (#50)
- [x] See the submission files (#52)
- [x] Leaderboard (#50)
- [x] Check for start_date > soft_deadline > hard_deadline (#41)
- [x] Accept submission only after start_date. (#53)
- [x] After hard_deadline, submissions will be accepted but this would not affect the final score of the Person-Problem (ie. do not update ppf after hard_deadline). This helps people solve problems after programming contests are over.
- [x] Delete button for Contest/Problem/Testcase (#47)
- [x] See and change TA score (#58)
- [x] CSV support for adding participants in bulk (#51)
- [x] Fix datetime issue in test (#51)
- [x] Download default scripts (compilation and test) when creating problem, and scripts after having created the problem. (#49)
- [x] Add option to enable linter scoring and/or TA scoring (#58)
- [x] Disable testcase, problem addition and deletion after start_date (#55, #58)
- [x] Do not show problems and contest before start_date to participants (#53)
- [x] Extend deadline (#57)
- [x] README.md (#59)
- [x] Documentation (#56)
- [x] Bug in downloading scores (Error when scores is `[])` (#54)
- [x] UI changes (#61)

**Comment by vishwakftw** [comment]
Can we please change the name of the application?

**Comment by vishwakftw** [comment]
Some suggestions:
- pp-judge
- auto-judge
- auto-score
